version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:afb41afcd1765a83193e55c3c25595cf40ea5f71
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
      - r-packages/deploy-package:
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger-revdeps:
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          plugins-branch: << pipeline.parameters.plugins-branch >>
          trigger-message: << pipeline.parameters.trigger-message >>
          triggered-packages: << pipeline.parameters.triggered-packages >>
